In [ ]:
# Using pip to install

pip install DefiLlama

In [17]:
# Importing relevant python pacakges

import pandas as pd
import numpy as np
import os
import json
from defillama import DefiLlama

In [37]:
# Endpoints are accessible without an API key

# initialize api client|
llama = DefiLlama()

# Get all protocols data
response = llama.get_all_protocols()

# Get a protocol data
response_1 = llama.get_protocol(name='uniswap')

# Get historical values of total TVL
response_2 = llama.get_historical_tvl()

# Get protocol TVL
response_3 = llama.get_protocol_tvl(name='Curve')

In [38]:
# Uniswap's TVL

response_1

18629897449.482304

In [84]:
# List all protocols 

#response

In [ ]:
#

response_1

In [85]:
# Created a DataFrame to structure by relevant parameters

defi_df = pd.DataFrame(response, 
                    columns =[
                        'name',
                        'symbol',
                        'tvl',
                        'fdv',
                        'mcap'
                    ])

defi_df.set_index('name',inplace=True)
defi_df.head()

               symbol             tvl            fdv           mcap
name
Curve             CRV 18629897449.482 7819104583.000  927863536.000
Lido              LDO 18321344373.237 2821117624.000  932828163.000
Anchor            ANC 16996826660.099 1915168150.000  657026938.000
MakerDAO          MKR 12853907541.786 1406539047.000 1260698128.000
Convex Finance    CVX 11435037792.427 2284996608.000 1383160483.000

In [86]:
defi_df1 = pd.DataFrame.from_dict(response)

defi_df1 = defi_df1[['name','symbol', 'tvl', 'fdv', 'mcap']]
defi_df1.set_index('symbol', inplace=True)
defi_df1

                  name             tvl            fdv           mcap
symbol
CRV              Curve 18629897449.482 7819104583.000  927863536.000
LDO               Lido 18321344373.237 2821117624.000  932828163.000
ANC             Anchor 16996826660.099 1915168150.000  657026938.000
MKR           MakerDAO 12853907541.786 1406539047.000 1260698128.000
CVX     Convex Finance 11435037792.427 2284996608.000 1383160483.000
...                ...             ...            ...            ...
CNDL            Candle           0.000   72186667.000          0.000
FLEX          CoinFLEX           0.000  374802540.000  298882220.000
SHIBUI      Shibui DAO           0.000    3130237.000          0.000
AMP             Ampere           0.000            NaN            NaN
LNS                LNS           0.000            NaN            NaN

[1567 rows x 4 columns]

In [30]:
# Changing scientific notation of values in table 

pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [31]:
# test

In [87]:
# Sort by highest TVL's 

defi_df.sort_values(by='tvl', ascending=False).head()

               symbol             tvl            fdv           mcap
name
Curve             CRV 18629897449.482 7819104583.000  927863536.000
Lido              LDO 18321344373.237 2821117624.000  932828163.000
Anchor            ANC 16996826660.099 1915168150.000  657026938.000
MakerDAO          MKR 12853907541.786 1406539047.000 1260698128.000
Convex Finance    CVX 11435037792.427 2284996608.000 1383160483.000

In [54]:
defi_df.dtypes

symbol        object
tvl          float64
chainTvls     object
mcap         float64
dtype: object

In [88]:
defi_df1= defi_df.loc[defi_df['tvl'] > 9000000000].copy()
defi_df1.sort_values(by='mcap', ascending=False).head(10)

,symbol,tvl,fdv,mcap
name,,,,
WBTC,WBTC,10315268927.460,10317317167.000,10317317167.000
Polygon Bridge & Staking,MATIC,9456344761.807,10574319658.000,7267613757.000
AAVE,AAVE,11244659103.887,2271890348.000,1945842931.000
Convex Finance,CVX,11435037792.427,2284996608.000,1383160483.000
MakerDAO,MKR,12853907541.786,1406539047.000,1260698128.000
Lido,LDO,18321344373.237,2821117624.000,932828163.000
Curve,CRV,18629897449.482,7819104583.000,927863536.000
Anchor,ANC,16996826660.099,1915168150.000,657026938.000

In [89]:
defi_df2 = defi_df1.loc[defi_df1['mcap'] < 10000000000].copy()
defi_df2.sort_values(by='tvl', ascending=False).head(10)

                         symbol             tvl             fdv           mcap
name
Curve                       CRV 18629897449.482  7819104583.000  927863536.000
Lido                        LDO 18321344373.237  2821117624.000  932828163.000
Anchor                      ANC 16996826660.099  1915168150.000  657026938.000
MakerDAO                    MKR 12853907541.786  1406539047.000 1260698128.000
Convex Finance              CVX 11435037792.427  2284996608.000 1383160483.000
AAVE                       AAVE 11244659103.887  2271890348.000 1945842931.000
Polygon Bridge & Staking  MATIC  9456344761.807 10574319658.000 7267613757.000

In [90]:
defi_df2['mcap_tvl_ratio'] = defi_df2['mcap'] / defi_df2['tvl'] 
defi_df2.sort_values(by='mcap_tvl_ratio', ).head(10)

,symbol,tvl,fdv,mcap,mcap_tvl_ratio
name,,,,,
Anchor,ANC,16996826660.099,1915168150.000,657026938.000,0.039
Curve,CRV,18629897449.482,7819104583.000,927863536.000,0.050
Lido,LDO,18321344373.237,2821117624.000,932828163.000,0.051
MakerDAO,MKR,12853907541.786,1406539047.000,1260698128.000,0.098
Convex Finance,CVX,11435037792.427,2284996608.000,1383160483.000,0.121
AAVE,AAVE,11244659103.887,2271890348.000,1945842931.000,0.173
Polygon Bridge & Staking,MATIC,9456344761.807,10574319658.000,7267613757.000,0.769

In [91]:
defi_df3 = defi_df2.loc[defi_df2['mcap_tvl_ratio'] < 0.5].copy()
defi_df3.sort_values(by='tvl', ascending=False).head(10)

,symbol,tvl,fdv,mcap,mcap_tvl_ratio
name,,,,,
Curve,CRV,18629897449.482,7819104583.000,927863536.000,0.050
Lido,LDO,18321344373.237,2821117624.000,932828163.000,0.051
Anchor,ANC,16996826660.099,1915168150.000,657026938.000,0.039
MakerDAO,MKR,12853907541.786,1406539047.000,1260698128.000,0.098
Convex Finance,CVX,11435037792.427,2284996608.000,1383160483.000,0.121
AAVE,AAVE,11244659103.887,2271890348.000,1945842931.000,0.173

In [92]:
defi_df3['fdv_tvl_ratio'] = defi_df3['fdv'] / defi_df3['tvl']
defi_df3

,symbol,tvl,fdv,mcap,mcap_tvl_ratio,fdv_tvl_ratio
name,,,,,,
Curve,CRV,18629897449.482,7819104583.000,927863536.000,0.050,0.420
Lido,LDO,18321344373.237,2821117624.000,932828163.000,0.051,0.154
Anchor,ANC,16996826660.099,1915168150.000,657026938.000,0.039,0.113
MakerDAO,MKR,12853907541.786,1406539047.000,1260698128.000,0.098,0.109
Convex Finance,CVX,11435037792.427,2284996608.000,1383160483.000,0.121,0.200
AAVE,AAVE,11244659103.887,2271890348.000,1945842931.000,0.173,0.202

In [94]:
# Market Cap / Total Value Locked RATIO :

# From a theoretical standpoint, the higher the TVL ratio is, the lower the value of an asset needs to be; however, this is not always the case when 
# we look at reality. One of the easiest ways to implement the TVL ratio is to help determine if a DeFi asset is undervalued or overvalued, and this can be done by looking at the ratio.
# If it is under 1/closer to 0, it is undervalued in most cases.

In [96]:
# Fully Dilluted Value / Total Value Locked RATIO: 

# Similar to MCAP/TVL , FDV/TVL helps us tell the whole story and is also measured the same. The closer the ratio is to zero, typically the coin is viewed as undervalued. 
#If it is over 1, it may be overvalued. Using both metrics helps provide us with the full picture.

In [ ]:
# Understanding Fully Diluted Valuation (FDV)

#The Fully Diluted Valuation of a cryptocurrency or token is what the digital asset's market cap would be if all the coins or tokens in its total supply were issued. Itâ€™s calculated by
#multiplying the current market price of a particular coin or token with the maximum number of coins there will be.