In [ ]:
# Using pip to install

pip install DefiLlama

In [17]:
# Importing relevant python pacakges

import pandas as pd
import numpy as np
import os
import json
from defillama import DefiLlama

In [37]:
# Endpoints are accessible without an API key

# initialize api client|
llama = DefiLlama()

# Get all protocols data
response = llama.get_all_protocols()

# Get a protocol data
response_1 = llama.get_protocol(name='uniswap')

# Get historical values of total TVL
response_2 = llama.get_historical_tvl()

# Get protocol TVL
response_3 = llama.get_protocol_tvl(name='Curve')

In [38]:
# Uniswap's TVL

response_1

18629897449.482304

In [84]:
# List all protocols 

#response

In [ ]:
#

response_1

In [59]:
# Created a DataFrame to structure by relevant parameters

defi_df = pd.DataFrame(response, 
                    columns =[
                        'name',
                        'symbol',
                        'tvl',
                        'mcap'
                    ])

defi_df.set_index('name',inplace=True)
defi_df.head()

               symbol             tvl           mcap
name
Curve             CRV 18629897449.482  927863536.000
Lido              LDO 18321344373.237  932828163.000
Anchor            ANC 16996826660.099  657026938.000
MakerDAO          MKR 12853907541.786 1260698128.000
Convex Finance    CVX 11435037792.427 1383160483.000

In [61]:
defi_df1 = pd.DataFrame.from_dict(response)

defi_df1 = defi_df1[['name','symbol', 'tvl', 'mcap']]
defi_df1.set_index('symbol', inplace=True)
defi_df1

                  name             tvl           mcap
symbol
CRV              Curve 18629897449.482  927863536.000
LDO               Lido 18321344373.237  932828163.000
ANC             Anchor 16996826660.099  657026938.000
MKR           MakerDAO 12853907541.786 1260698128.000
CVX     Convex Finance 11435037792.427 1383160483.000
...                ...             ...            ...
CNDL            Candle           0.000          0.000
FLEX          CoinFLEX           0.000  298882220.000
SHIBUI      Shibui DAO           0.000          0.000
AMP             Ampere           0.000            NaN
LNS                LNS           0.000            NaN

[1567 rows x 3 columns]

In [30]:
# Changing scientific notation of values in table 

pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [31]:
# test

In [62]:
# Sort by highest TVL's 

defi_df.sort_values(by='tvl', ascending=False).head()

               symbol             tvl           mcap
name
Curve             CRV 18629897449.482  927863536.000
Lido              LDO 18321344373.237  932828163.000
Anchor            ANC 16996826660.099  657026938.000
MakerDAO          MKR 12853907541.786 1260698128.000
Convex Finance    CVX 11435037792.427 1383160483.000

In [54]:
defi_df.dtypes

symbol        object
tvl          float64
chainTvls     object
mcap         float64
dtype: object

In [63]:
defi_df1= defi_df.loc[defi_df['tvl'] > 9000000000].copy()
defi_df1.sort_values(by='mcap', ascending=False).head(10)

                         symbol             tvl            mcap
name
WBTC                       WBTC 10315268927.460 10317317167.000
Polygon Bridge & Staking  MATIC  9456344761.807  7267613757.000
AAVE                       AAVE 11244659103.887  1945842931.000
Convex Finance              CVX 11435037792.427  1383160483.000
MakerDAO                    MKR 12853907541.786  1260698128.000
Lido                        LDO 18321344373.237   932828163.000
Curve                       CRV 18629897449.482   927863536.000
Anchor                      ANC 16996826660.099   657026938.000

In [75]:
defi_df2 = defi_df1.loc[defi_df1['mcap'] < 10000000000].copy()
defi_df2.sort_values(by='tvl', ascending=False).head(10)

                         symbol             tvl           mcap
name
Curve                       CRV 18629897449.482  927863536.000
Lido                        LDO 18321344373.237  932828163.000
Anchor                      ANC 16996826660.099  657026938.000
MakerDAO                    MKR 12853907541.786 1260698128.000
Convex Finance              CVX 11435037792.427 1383160483.000
AAVE                       AAVE 11244659103.887 1945842931.000
Polygon Bridge & Staking  MATIC  9456344761.807 7267613757.000

In [79]:
defi_df2['mcap_tvl_ratio'] = defi_df2['mcap'] / defi_df2['tvl'] 
defi_df2.sort_values(by='mcap_tvl_ratio', ).head(10)

                         symbol             tvl           mcap  mcap_tvl_ratio
name
Anchor                      ANC 16996826660.099  657026938.000           0.039
Curve                       CRV 18629897449.482  927863536.000           0.050
Lido                        LDO 18321344373.237  932828163.000           0.051
MakerDAO                    MKR 12853907541.786 1260698128.000           0.098
Convex Finance              CVX 11435037792.427 1383160483.000           0.121
AAVE                       AAVE 11244659103.887 1945842931.000           0.173
Polygon Bridge & Staking  MATIC  9456344761.807 7267613757.000           0.769

In [82]:
defi_df3 = defi_df2.loc[defi_df2['mcap_tvl_ratio'] < 0.5].copy()
defi_df3.sort_values(by='tvl', ascending=False).head(10)

               symbol             tvl           mcap  mcap_tvl_ratio
name
Curve             CRV 18629897449.482  927863536.000           0.050
Lido              LDO 18321344373.237  932828163.000           0.051
Anchor            ANC 16996826660.099  657026938.000           0.039
MakerDAO          MKR 12853907541.786 1260698128.000           0.098
Convex Finance    CVX 11435037792.427 1383160483.000           0.121
AAVE             AAVE 11244659103.887 1945842931.000           0.173